### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by yamandu** [UnevenSoftware/vue-insta-stories#2]
When trying to run the example I got these two errors and it displays nothing.

Missing required prop: "story"
TypeError: Cannot read property 'url' of undefined

Looks like it can't pass down the parameters (stories) at some point.
I tried to fix that but I was not able to find the exact line it messes with the parameters yet.
This component is awesome, any help on fixing this will be appreciated.

I created a new vue project with 
`vue create`
and add the modules 
```
yarn add vue-insta-stories
yarn add @vue/composition-api

```
My code:

```
<template>
  <div id="app">
    <Stories :stories="items" />
  </div>
</template>

<script>
import { Stories } from "vue-insta-stories";

export default {
  name: 'App',
  components: {
    Stories
  },
  data: () => ({
    items: [
      "https://picsum.photos/350/200/",
      "https://picsum.photos/400/201/",
      {
        url: "https://file-examples-com.github.io/5mb.mp4",
        type: "video",
      },
    ]
  })
}
</script>
```

**Comment by gilnd** [comment]
Hey @yamandu,
Thanks for reporting the issue.

May i ask what version of vue you're using?

**Comment by gilnd** [comment]
Hey @yamandu,
Thanks for reporting the issue.

May i ask what version of vue you're using?

**Comment by gilnd** [comment]
Hey @yamandu,
Thanks for reporting the issue.

Are you using vue2?

Can you also provide the full log?

Thanks.

**Comment by dnldsht** [comment]
I'm glad that you are using our library!

Found out that vue-demi doesn't work the same on vue2 and vue3.
A new release (0.9.1)  is available, it should fix the issue (let me now if it works for you)
