### ISSUE TITLE
Loading Story media from file system

### ISSUE THREAD

**Issue by VasilijeBursac** [UnevenSoftware/vue-insta-stories#4]
Hello,

Is it possible to load images/videos from the file system (for example the `assets` folder)?

I tried to load items from the `assets` folder by putting the path to an exact file in the `items` list, but it doesn't load the image, I just get an empty story with a **"broken image" icon** at the top.

The only thing that I have changed in code from your documentation is adding the path to my file in the `items` list, like this:

```
items: [
        "../assets/logo.png",
        "https://picsum.photos/350/200/",
        "https://picsum.photos/400/201/",
        {
            url: "https://file-examples-com.github.io/5mb.mp4",
            type: "video",
        },
        ]

```

This component is awesome, any help on fixing this will be appreciated! 
Thanks in advance! 
Best regards! 😄

**Comment by dnldsht** [comment]
Hi there! I'm glad that you are enjoying this library :heart: 
The image render is very simple its just a <img /> tag so whatever works on an img wold work on vue-insta-stories

if you want to load images from the project folder you can

1. use the `public` folder, (vue serve every file that is there). so if you have the file `public/logo.png` you can have the item `/logo.png`
2. use the asset folder, since the resources that are there are bundled you cant use `"../assets/logo.png"` from the script, but you can do
```js
// in vue 2
items: [
 require("../assets/logo.png")
]

// in vue 3 using vite require doesn't for me this way it works 
import staticAsset from "./assets/lavader.jpg";
items: [
 staticAsset
]
```
3. use base64 images

**Comment by VasilijeBursac** [comment]
> Hi there! I'm glad that you are enjoying this library ❤️
> The image render is very simple its just a  tag so whatever works on an img wold work on vue-insta-stories
> 
> if you want to load images from the project folder you can
> 
> use the public folder, (vue serve every file that is there). so if you have the file public/logo.png you can have the item /logo.png
> use the asset folder, since the resources that are there are bundled you cant use "../assets/logo.png" from the script, but you can do
> // in vue 2
> items: [
>  require("../assets/logo.png")
> ]
> 
> // in vue 3 using vite require doesn't for me this way it works 
> import staticAsset from "./assets/lavader.jpg";
> items: [
>  staticAsset
> ]
> use base64 images

Thank you so much for your answer! 

Using `require("../assets/logo.png")` worked immediately! 😄 
Do the same rules apply to importing videos?

Best regards!

**Comment by dnldsht** [comment]
Yes require should work with all the static assets, never used with videos
but should work

**Comment by VasilijeBursac** [comment]
> Yes require should work with all the static assets, never used with videos but should work

`require` works fine with the video, too. I have tried it now. Thank you very much!
